---
modules-search: [ local ]

branding: ion

instances:
    - id: pacman-init
      module: shellprocess
      config: shellprocess-pacman-init.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - netinstall
      - users
      - summary

  - exec:
      - partition
      - mount
      - unpackfs
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - shellprocess@pacman-init
      - packages
      - shellprocess
      - umount

  - show:
      - finished

prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false
