---
groupsUrl: local
required: false

label:
    sidebar: "Packages"

groups:
    - name: "Applications"
      description: "Optional applications"
      selected: false
      critical: false
      expanded: true
      subgroups: []
