---
efiSystemPartition: /boot
efiSystemPartitionSize: 1024M
efiSystemPartitionName: EFI

defaultFileSystemType: btrfs
availableFileSystemTypes:
    - ext4
    - btrfs
    - xfs

enableLuksAutomatedPartitioning: false

drawNestedPartitions: false
alwaysShowPartitionLabels: true

initialPartitioningChoice: erase
initialSwapChoice: small

defaultPartitionTableType: gpt
