---
dontChroot: false
timeout: 300

script:
  - command: "/bin/bash -c 'printf \"%s\\n\" \"NAME=Ion Linux\" \"PRETTY_NAME=Ion Linux\" \"ID=ion\" \"ID_LIKE=arch\" \"BUILD_ID=rolling\" \"ANSI_COLOR=38;2;23;147;209\" \"HOME_URL=https://ionlinux.org/\" \"DOCUMENTATION_URL=https://wiki.ionlinux.org/\" \"SUPPORT_URL=https://forum.ionlinux.org/\" \"BUG_REPORT_URL=https://bugs.ionlinux.org/\" \"LOGO=ion-logo\" > /etc/os-release'"
  - "-/bin/bash -c 'cp /usr/share/pixmaps/ion-logo.svg /usr/share/pixmaps/archlinux-logo.svg; cp /usr/share/pixmaps/ion-logo-text-dark.svg /usr/share/pixmaps/archlinux-logo-text.svg; cp /usr/share/pixmaps/ion-logo-text.svg /usr/share/pixmaps/archlinux-logo-text-dark.svg; true'"
  - "/bin/bash /etc/calamares/scripts/fix-initramfs.sh"
  - "systemctl enable NetworkManager"
