---
defaultGroups:
    - name: wheel
      must_exist: false
      system: true
    - name: users
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: render
      must_exist: false
      system: true

autologinGroup: autologin

sudoersGroup: wheel
sudoersConfigureWithGroup: true

setRootPassword: true
doAutologin: false

passwordRequirements:
    minLength: 1
    maxLength: -1
