---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 8
    requiredRam: 1.0
    internetCheckUrl: https://archlinux.org
    check:
        - storage
        - ram
        - root
        - internet
    required:
        - storage
        - ram
        - root
